# turns off email notifications:
  notifications:
    email: false

# run checks on Markdown writing through proselint script:
  # Markdown
  language: python
  python:
    - "3.5"

  before_install:
  - gem install mdl

  install:
  - pip install --upgrade pip
  - pip install proselint
  # - npm install htmlhint -g

  script:
  - proselint README.md
  - mdl README.md
  # - htmlhint www.mendezjw.com/index.html
